server:
  name: deposition-curation
  port: 80

logging:
  level:
    org:
      springframework: ERROR


gwas-curation:
  auth:
    enabled: false
    cert: aap.der
    auto-curator-service-account: auto-curator-service@ebi.ac.uk
    curators:
      auth-mechanism: JWT_DOMAIN
      jwt-domains: self.GWAS_Curator
  solr:
    enabled: true

spring:
  profiles:
    active: local
  mail:
    host: hh-smtp.ebi.ac.uk
    port: 25
    properties:
      mail:
        smtp:
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
          auth: false
          sendpartial: true
          starttls:
            enable: true

email:
  enabled: true
  config:
    from-address: no-reply@ebi.ac.uk
    from-name: GWAS Rabbit Consumer
    retries: 3

email-config:
  to-address: gwas-curator@ebi.ac.uk,gwas-dev-logs@ebi.ac.uk


comms:
  messaging:
    enabled: false




europepmc:
  root: https://www.ebi.ac.uk/europepmc/webservices/rest/
  search:
    pubmed: search?query=ext_id:{idlist} src:med&resulttype=core&format=JSON