server:
  port: 8685
  servlet:
    context-path: /gwas/diagram-api

url:
  efo: http://ves-oy-7e.ebi.ac.uk:8080/gwas/api/v2/efotraits/%s/traits/children
  ols: https://www.ebi.ac.uk/ols4/api/ontologies/efo/hierarchicalDescendants?id=%s&size=1000
  solr:
  server:


spring:
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  main:
    allow-circular-references: true





springdoc:
  api-docs:
    path: api-docs


